AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Create one EC2 instance in the account's default VPC, a KeyPair (private key
  stored in SSM Parameter Store), and a Security Group allowing 22, 80, 443.

Parameters:
  KeyName:
    Type: String
    Default: cfn-demo-key
    Description: >
      Name for the KeyPair to create. CloudFormation will store the private key
      in SSM Parameter Store at /ec2/keypair/{key_pair_id}.

  SSHLocation:
    Type: String
    Default: 0.0.0.0/0
    Description: CIDR to allow SSH from. (Use YOUR_IP/32 in production)

  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type.

  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
    Description: Amazon Linux 2 AMI ID (pulled from SSM public parameter).

Resources:
  NewKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Ref KeyName
      KeyType: rsa
      KeyFormat: pem

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH(22), HTTP(80), HTTPS(443)
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref NewKeyPair
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: CFN-Single-EC2

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref Ec2Instance

  InstancePublicIp:
    Description: Public IP of the EC2 instance
    Value: !GetAtt Ec2Instance.PublicIp
